# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Microsoft.PowerBI_Pckgr
PackageVersion: 2.128.1177.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 6.2.9200
InstallerType: burn
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: -silent -norestart
  SilentWithProgress: -passive -norestart
  InstallLocation: INSTALLLOCATION="<INSTALLPATH>"
  Log: -log "<LOGPATH>"
  Upgrade: -update
  Custom: ACCEPT_EULA=1
UpgradeBehavior: install
ProductCode: '{13e4778c-60bf-4f25-ae13-66248f27d154}'
AppsAndFeaturesEntries:
- DisplayName: Microsoft PowerBI Desktop (x64)
  Publisher: Microsoft Corporation
  ProductCode: '{13e4778c-60bf-4f25-ae13-66248f27d154}'
  InstallerType: burn
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup-2024-03_x64.exe
  InstallerSha256: 8CA227768066DE97DF883CFECFEC5D4CD92514DA1799170DF9FCD37B574A9B8D
ManifestType: installer
ManifestVersion: 1.6.0
