# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Zoom.ZoomOutlookPlugin_Pckgr
PackageVersion: 6.0.0.1012
PackageLocale: en-US
Publisher: Zoom
PublisherUrl: https://zoom.us/
PublisherSupportUrl: https://support.zoom.us/
PrivacyUrl: https://explore.zoom.us/en/privacy/
Author: Zoom Video Communications, Inc.
PackageName: Zoom Outlook Plugin
PackageUrl: https://zoom.us/
License: Proprietary
LicenseUrl: https://explore.zoom.us/en/terms/
Copyright: Copyright ©2012-2022 Zoom Video Communications, Inc. All rights reserved.
ShortDescription: The Zoom Plugin for Outlook installs a button on the Microsoft Outlook tool bar to enable you to start or schedule a meeting with one-click.
Tags:
- outlook
- zoom
ManifestType: defaultLocale
ManifestVersion: 1.6.0
