# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Zoom.Zoom_Pckgr
PackageVersion: 6.0.3.37634
UpgradeBehavior: install
Protocols:
- zoom
- zoommtg
FileExtensions:
- zoommtg
- zoomphonecall
Installers:
- Architecture: x86
  InstallerType: exe
  Scope: user
  InstallerUrl: https://zoom.us/client/6.0.3.37634/ZoomInstallerFull.exe
  InstallerSha256: 203E414604B89A1E2EE604A88FE0971714960EEFCC348C51D1AF908C91DE3459
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent
    SilentWithProgress: /silent
  ProductCode: ZoomUMX
  AppsAndFeaturesEntries:
  - Publisher: Zoom Video Communications, Inc.
    DisplayVersion: 5.17.10 (33775)
    ProductCode: ZoomUMX
- Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://zoom.us/client/6.0.3.37634/ZoomInstallerFull.exe?archType=x64
  InstallerSha256: 421FE886EBE308FFE0C9FF6A671D98B7F885AB7AC10DAFF7AD20ABC81DC627EC
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent
    SilentWithProgress: /silent
  ProductCode: ZoomUMX
  AppsAndFeaturesEntries:
  - Publisher: Zoom Video Communications, Inc.
    DisplayVersion: 5.17.10 (33775)
    ProductCode: ZoomUMX
- Architecture: arm64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://zoom.us/client/6.0.3.37634/ZoomInstallerFull.exe?archType=winarm64
  InstallerSha256: 3C9189C3A61CE1B61EC9F05210AA0A423D159534088871A75EF7F21C9E6B7AF7
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent
    SilentWithProgress: /silent
  ProductCode: ZoomUMX
  AppsAndFeaturesEntries:
  - Publisher: Zoom Video Communications, Inc.
    DisplayVersion: 5.17.10 (33775)
    ProductCode: ZoomUMX
- Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://zoom.us/client/6.0.3.37634/ZoomInstallerFull.msi
  InstallerSha256: 47AD56E363CCC09A18BAC285252371BA3D9DE952D4631BB5A9C70D67C31C7B3E
  ProductCode: '{55A322F6-C59C-4FF5-A489-A3CD44147010}'
  AppsAndFeaturesEntries:
  - DisplayName: Zoom (32-bit)
    DisplayVersion: 5.17.10.33775
    ProductCode: '{78226EBD-E927-40BC-A53A-DC9BF255C3B1}'
    UpgradeCode: '{C819B794-A45C-4F27-9860-0C86492A52CC}'
- Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://zoom.us/client/6.0.3.37634/ZoomInstallerFull.msi?archType=x64
  InstallerSha256: B1D720860657B7F15A8511DB4EA8B028CA7D48A1178A1B6C2A712F085D7C187D
  ProductCode: '{DFA1B257-CC53-431B-9492-97D0FB3D4432}'
  AppsAndFeaturesEntries:
  - DisplayName: Zoom (64-bit)
    DisplayVersion: 5.17.10.33775
    ProductCode: '{CEDE24AC-2B05-4B73-9604-93E8EF2398E9}'
    UpgradeCode: '{C819B794-A45C-4F27-9860-0C86492A52CC}'
- Architecture: arm64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://zoom.us/client/6.0.3.37634/ZoomInstallerFull.msi?archType=winarm64
  InstallerSha256: 1761BA04B2DE35DC8B3CA86DE7B7A2DDF3C2DB01A4634BBFDDC8FB8109BFC3F4
  ProductCode: '{108B13C5-5180-4C3E-87EF-1BCE17A91FD5}'
  AppsAndFeaturesEntries:
  - DisplayName: Zoom (ARM64)
    DisplayVersion: 5.17.10.33775
    ProductCode: '{AB4AAAA7-9E5C-44DA-B25B-59AB2475EB93}'
    UpgradeCode: '{C819B794-A45C-4F27-9860-0C86492A52CC}'
ManifestType: installer
ManifestVersion: 1.6.0
