# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Zoom.Zoom_Pckgr
PackageVersion: 6.0.0.37205
UpgradeBehavior: install
Protocols:
- zoom
- zoommtg
FileExtensions:
- zoommtg
- zoomphonecall
Installers:
- Architecture: x86
  InstallerType: exe
  Scope: user
  InstallerUrl: https://zoom.us/client/6.0.0.37205/ZoomInstallerFull.exe
  InstallerSha256: 0CFB36A454CAEF5B86F4642C2B90ECE66D1C4B0FA6A90EEB70A82493DECEEFE8
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent
    SilentWithProgress: /silent
  ProductCode: ZoomUMX
  AppsAndFeaturesEntries:
  - Publisher: Zoom Video Communications, Inc.
    DisplayVersion: 5.17.10 (33775)
    ProductCode: ZoomUMX
- Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://zoom.us/client/6.0.0.37205/ZoomInstallerFull.exe?archType=x64
  InstallerSha256: 9D2A2866CAC63FE0EC155CF75A8BD836B3E1284B394B896E2C34FEC0331FFF9C
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent
    SilentWithProgress: /silent
  ProductCode: ZoomUMX
  AppsAndFeaturesEntries:
  - Publisher: Zoom Video Communications, Inc.
    DisplayVersion: 5.17.10 (33775)
    ProductCode: ZoomUMX
- Architecture: arm64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://zoom.us/client/6.0.0.37205/ZoomInstallerFull.exe?archType=winarm64
  InstallerSha256: 4AC91A97D1716AD8348006F2C18FE8390F45A0A1C3175D246F27F21B363228E3
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent
    SilentWithProgress: /silent
  ProductCode: ZoomUMX
  AppsAndFeaturesEntries:
  - Publisher: Zoom Video Communications, Inc.
    DisplayVersion: 5.17.10 (33775)
    ProductCode: ZoomUMX
- Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://zoom.us/client/6.0.0.37205/ZoomInstallerFull.msi
  InstallerSha256: 4EA8D109D1A03F2F0377AA05953001047CD0B03541DCBB8BED61FB8FC9B6B904
  ProductCode: '{C740E787-A247-4688-B1EF-8DD2FF908709}'
  AppsAndFeaturesEntries:
  - DisplayName: Zoom (32-bit)
    DisplayVersion: 5.17.10.33775
    ProductCode: '{78226EBD-E927-40BC-A53A-DC9BF255C3B1}'
    UpgradeCode: '{C819B794-A45C-4F27-9860-0C86492A52CC}'
- Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://zoom.us/client/6.0.0.37205/ZoomInstallerFull.msi?archType=x64
  InstallerSha256: F6181623A856E82C59B632AC371E8FDDA267F857D1E4364CE9046CFB362F2672
  ProductCode: '{D0195CC7-CF89-4261-8E71-3C5B4442FA0E}'
  AppsAndFeaturesEntries:
  - DisplayName: Zoom (64-bit)
    DisplayVersion: 5.17.10.33775
    ProductCode: '{CEDE24AC-2B05-4B73-9604-93E8EF2398E9}'
    UpgradeCode: '{C819B794-A45C-4F27-9860-0C86492A52CC}'
- Architecture: arm64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://zoom.us/client/6.0.0.37205/ZoomInstallerFull.msi?archType=winarm64
  InstallerSha256: 4EF7C55ADD5A6026397E9E7B5B8DF5D71FF91C738C60BA7EFEE3E9564C6D7A0D
  ProductCode: '{D6926A24-770A-42C3-A540-11DC640F7C2A}'
  AppsAndFeaturesEntries:
  - DisplayName: Zoom (ARM64)
    DisplayVersion: 5.17.10.33775
    ProductCode: '{AB4AAAA7-9E5C-44DA-B25B-59AB2475EB93}'
    UpgradeCode: '{C819B794-A45C-4F27-9860-0C86492A52CC}'
ManifestType: installer
ManifestVersion: 1.6.0
