# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Logitech.Sync_Pckgr
PackageVersion: 3.3.176.0
MinimumOSVersion: 10.0.0.0
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
ProductCode: LogiSync
Installers:
- Architecture: x64
  InstallerUrl: https://software.vc.logitech.com/downloads/sync/LogiSyncApp-Setup.exe
  InstallerSha256: FF21E7833DFD212B351D8BC1BF831C65D0FCF0F5D2FCA31D004864D2FE90F6CD
ManifestType: installer
ManifestVersion: 1.6.0
