# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Egnyte.EgnyteDesktopApp_Pckgr
PackageVersion: 3.17.0.143
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{4B546EEB-39BA-4D66-86DD-B64A16C2ADE5}'
AppsAndFeaturesEntries:
- UpgradeCode: '{03909D9B-F5F2-41F3-ABF9-4FCE077F028D}'
Installers:
- Architecture: x64
  InstallerUrl: https://egnyte-cdn.egnyte.com/egnytedrive/win/en-us/latest/EgnyteConnectWin.msi
  InstallerSha256: 6EC8223CC2ECD2A9E9D38371FB27EC07B6CB3CDAA562CB570793DC27D95FABA7
ManifestType: installer
ManifestVersion: 1.6.0
